### ISSUE TITLE
Post formats

### ISSUE THREAD

**Issue by ernilambar** [AlxMedia/kontrast#10]
* Do we need `post-formats.js`?
* We need to check other post format related stuffs also.

Reason: Keeping fields like audio URL, video URL, etc is not allowed.

**Comment by AlxMedia** [comment]
Are these fields allowed to be added via a companion plugin or not at all?

**Comment by ernilambar** [comment]
In plugin, we can add any field we want :-)

**Comment by ernilambar** [comment]
Fixed https://github.com/AlxMedia/kontrast/pull/20
