### ISSUE TITLE
Removing `title` attribute from links

### ISSUE THREAD

**Issue by ernilambar** [AlxMedia/kontrast#12]
From Accessibility point of view, it is good to avoid `title` attribute in links.

**Comment by AlxMedia** [comment]
Is this specifically for the social links, or are there more instances?

**Comment by AlxMedia** [comment]
Removed most of them with https://github.com/AlxMedia/kontrast/commit/9cbdfd64ec476c36831d53e3a38e08e819196773, only kept a few places for "hover-understanding", like for the tabs widget that has no texts, just icons. Same for the social links, it needs the title attribute for the css styling (the bubble). Is that okay?

**Comment by ernilambar** [comment]
This is not "required". Remove as much as possible. Keep if needed.

**Comment by AlxMedia** [comment]
Alright, good - I'm avoiding it as much as possible and keeping only where needed. I think this can be closed then.
