### ISSUE TITLE
Custom sidebar creation

### ISSUE THREAD

**Issue by ernilambar** [AlxMedia/kontrast#9]
This feature falls under plugin territory. Needs to be removed.

**Comment by AlxMedia** [comment]
Could this functionality be added to my companion plugin? https://github.com/AlxMedia/alx-extensions

Many users would be unhappy with it completely removed.

**Comment by ernilambar** [comment]
We can move this feature to the plugin.

**Comment by AlxMedia** [comment]
Would be great!

**Comment by AlxMedia** [comment]
Is it possible to add a "Theme Extensions" section in the live customizer below "Theme Options" and have on/off options for social links, thumbnail upscale and a sub-section for the custom sidebar creation? 

Not sure how advanced that would be, just an idea. Perhaps you have some other plan :-)

**Comment by ernilambar** [comment]
Fixed
